import Footer from "@/components/footer";
import type { Metadata } from "next";
import { Anton, DM_Sans } from "next/font/google";
import "./globals.css";

const anton = Anton({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-anton",
});

const DMSans = DM_Sans({
  subsets: ["latin"],
  weight: "600",
  variable: "--font-dmsans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${anton.variable} ${DMSans.variable}  bg-blue-primary antialiased`}
      >
        <div className="z-10">{children}</div>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
